// comics.js — master comic data (30 comics)

window.COMICS = [
  // ---------------------- NEW RELEASES ----------------------
  {
    id: 1,
    title: "Spider-Man: New Dawn",
    publisher: "Marvel",
    price: 299,
    cover: "assets/marvel/spiderman.jpg",
    category: "new",
  },
  {
    id: 2,
    title: "Batman: Shadows",
    publisher: "DC",
    price: 349,
    cover: "assets/dc/bat.jpg",
    category: "new",
  },
  {
    id: 3,
    title: "Invincible: Reborn",
    publisher: "Image",
    price: 399,
    cover: "assets/marvel/invincible.jpg",
    category: "new",
  },
  {
    id: 4,
    title: "Thor: Godbreaker",
    publisher: "Marvel",
    price: 330,
    cover: "assets/marvel/thor.jpg",
    category: "new",
  },
  {
    id: 5,
    title: "Wonder Woman: Divine War",
    publisher: "DC",
    price: 360,
    cover: "assets/dc/wonder woman.jpg",
    category: "new",
  },
  {
    id: 6,
    title: "Saga: Starfall",
    publisher: "Image",
    price: 350,
    cover: "assets/image/saga.jpg",
    category: "new",
  },

  // ---------------------- POPULAR SERIES ----------------------
  {
    id: 7,
    title: "X-Men: Phoenix Rising",
    publisher: "Marvel",
    price: 299,
    cover: "assets/marvel/x men.jpg",
    category: "popular",
  },
  {
    id: 8,
    title: "Superman: Legacy",
    publisher: "DC",
    price: 399,
    cover: "assets/dc/superman.jpg",
    category: "popular",
  },
  {
    id: 9,
    title: "Avengers: Eternal Storm",
    publisher: "Marvel",
    price: 399,
    cover: "assets/marvel/avengers.jpg",
    category: "popular",
  },
  {
    id: 10,
    title: "Flash: Velocity Surge",
    publisher: "DC",
    price: 320,
    cover: "assets/dc/Flash.jpg",
    category: "popular",
  },
  {
    id: 11,
    title: "Spawn: Hell Rises",
    publisher: "Image",
    price: 380,
    cover: "assets/image/Spawn.jpg",
    category: "popular",
  },
  {
    id: 12,
    title: "The Walking Dead: Afterlife",
    publisher: "Image",
    price: 320,
    cover: "assets/image/walking dead.jpg",
    category: "popular",
  },

  // ---------------------- MARVEL ----------------------
  {
    id: 13,
    title: "Iron Man: Armored Vengeance",
    publisher: "Marvel",
    price: 350,
    cover: "assets/marvel/iron man.jpg",
    category: "regular",
  },
  {
    id: 14,
    title: "Black Panther: Wakanda Legacy",
    publisher: "Marvel",
    price: 320,
    cover: "assets/marvel/black panther.jpg",
    category: "regular",
  },
  {
    id: 15,
    title: "Hulk: Gamma Rage",
    publisher: "Marvel",
    price: 280,
    cover: "assets/marvel/hulk.jpg",
    category: "regular",
  },
  {
    id: 16,
    title: "Doctor Strange: Mystic Realms",
    publisher: "Marvel",
    price: 360,
    cover: "assets/marvel/doctot strange.jpg",
    category: "regular",
  },

  // ---------------------- DC ----------------------
  {
    id: 17,
    title: "Aquaman: Abyssal Crown",
    publisher: "DC",
    price: 310,
    cover: "assets/dc/aquaman.jpg",
    category: "regular",
  },
  {
    id: 18,
    title: "Green Lantern: Cosmic Oath",
    publisher: "DC",
    price: 350,
    cover: "assets/dc/Green Lantern.jpg",
    category: "regular",
  },
  {
    id: 19,
    title: "Shazam: Thunder Born",
    publisher: "DC",
    price: 330,
    cover: "assets/dc/shazam.jpg",
    category: "regular",
  },
  {
    id: 20,
    title: "Joker: Laughing Madness",
    publisher: "DC",
    price: 340,
    cover: "assets/dc/joker.jpg",
    category: "regular",
  },

  // ---------------------- IMAGE ----------------------
  {
    id: 21,
    title: "Witchblade: Bloodline",
    publisher: "Image",
    price: 310,
    cover: "assets/image/Witchblade.jpg",
    category: "regular",
  },
  {
    id: 22,
    title: "Kick-Ass: Rebellion",
    publisher: "Image",
    price: 280,
    cover: "assets/image/Kick ass.jpg",
    category: "regular",
  },
  {
    id: 23,
    title: "Haunt: Phantoms Unleashed",
    publisher: "Image",
    price: 330,
    cover: "assets/image/haunt.jpg",
    category: "regular",
  },
  {
    id: 24,
    title: "The Darkness: Void Rising",
    publisher: "Image",
    price: 350,
    cover: "assets/image/darkness.jpeg",
    category: "regular",
  },
  {
    id: 25,
    title: "Monstress: Dragonspire",
    publisher: "Image",
    price: 360,
    cover: "assets/image/monstress.jpg",
    category: "regular",
  },
  {
    id: 26,
    title: "Shadowhawk: Night Assault",
    publisher: "Image",
    price: 280,
    cover: "assets/image/shadowhawk.jpg",
    category: "regular",
  },

  // ---------------------- EXTRA ----------------------
  {
    id: 27,
    title: "Captain America: Sentinel",
    publisher: "Marvel",
    price: 300,
    cover: "assets/marvel/captain america.jpg",
    category: "regular",
  },
  {
    id: 28,
    title: "Green Arrow: Silent Hunt",
    publisher: "DC",
    price: 310,
    cover: "assets/dc/greenarrow.jpg",
    category: "regular",
  },
  {
    id: 29,
    title: "Saga: Moonfall",
    publisher: "Image",
    price: 340,
    cover: "assets/image/sag.jpeg",
    category: "regular",
  },
  {
    id: 30,
    title: "Avengers: Titan Assault",
    publisher: "Marvel",
    price: 420,
    cover: "assets/marvel/avengerst.jpg",
    category: "regular",
  },
];
